# Generated by Django 4.0.4 on 2022-06-10 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idCategoria', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID de Categoría')),
                ('nombreCategoria', models.CharField(max_length=30, verbose_name='Nombre de Categoría')),
            ],
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('nombre', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Nombre')),
                ('email', models.CharField(max_length=10, verbose_name='Correo')),
                ('telefono', models.CharField(max_length=10, verbose_name='Telefono')),
                ('comentario', models.CharField(max_length=10, verbose_name='Comentario')),
            ],
        ),
    ]
