# Generated by Django 4.0.4 on 2022-06-10 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Jardineria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='nombreCategoria',
            field=models.CharField(max_length=40, verbose_name='Nombre de Categoría'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='comentario',
            field=models.CharField(max_length=40, verbose_name='Comentario'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='email',
            field=models.CharField(max_length=40, verbose_name='Correo'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='nombre',
            field=models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='telefono',
            field=models.CharField(max_length=40, verbose_name='Telefono'),
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('nombre', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='Nombre')),
                ('cantidad', models.CharField(max_length=40, verbose_name='Cantidad Disponible')),
                ('precio', models.CharField(max_length=40, verbose_name='Precio')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Jardineria.categoria')),
            ],
        ),
    ]
