# Generated by Django 4.0.4 on 2022-06-11 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jardineria', '0003_alter_contacto_telefono_alter_producto_cantidad_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('nombre', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='Nombre')),
                ('perfil', models.ImageField(null=True, upload_to='Cliente')),
                ('email', models.CharField(max_length=40, verbose_name='Correo')),
                ('direccion', models.CharField(max_length=40, verbose_name='Direccion')),
                ('comuna', models.CharField(max_length=40, verbose_name='Comuna')),
                ('cuidad', models.CharField(max_length=40, verbose_name='Cuidad')),
                ('telefono', models.IntegerField(verbose_name='Telefono')),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='foto',
            field=models.ImageField(null=True, upload_to='Producto'),
        ),
    ]
