# Generated by Django 4.0.4 on 2022-06-12 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jardineria', '0008_remove_cliente_cuidad_cliente_region_cliente_rut_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='region',
            field=models.CharField(max_length=40, verbose_name='Region'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='rut',
            field=models.CharField(max_length=40, verbose_name='Rut'),
        ),
    ]
